"""Generate a starter distill JSON for a new provider (onboarding)."""

from __future__ import annotations

import json
from datetime import date
from typing import Any

from tollgate.distill.loader import distill_dir
from tollgate.distill.schema import validate_distill


AUTH_PRESETS: dict[str, dict[str, Any]] = {
    "bearer": {
        "type": "bearer",
        "header": "Authorization",
        "env": [],
        "summary": "Authorization: Bearer <KEY>",
    },
    "header_token": {
        "type": "header_token",
        "header": "X-Api-Key",
        "env": [],
        "summary": "X-Api-Key: <KEY>",
    },
    "xi_api_key": {
        "type": "header_token",
        "header": "xi-api-key",
        "env": [],
        "summary": "xi-api-key: <KEY>",
    },
}


def scaffold_provider(
    provider_id: str,
    *,
    title: str = "",
    base_url: str = "",
    auth: str = "bearer",
    env_key: str = "",
    high_risk: bool = False,
    write: bool = True,
) -> dict[str, Any]:
    """
    Create distill/<id>.json skeleton.

    auth: bearer | header_token | xi_api_key
    """
    pid = (provider_id or "").strip().lower().replace(" ", "_")
    if not pid or "/" in pid or "\\" in pid:
        return {"ok": False, "error": "invalid provider id"}
    path = distill_dir() / f"{pid}.json"
    if path.is_file():
        return {"ok": False, "error": f"already exists: {path.name}", "path": str(path)}

    env = (env_key or f"{pid.upper()}_API_KEY").strip()
    preset = dict(AUTH_PRESETS.get(auth) or AUTH_PRESETS["bearer"])
    preset["env"] = [env]
    if auth == "bearer":
        preset["summary"] = f"Authorization: Bearer <{env}>"
    elif auth == "header_token":
        preset["summary"] = f"{preset.get('header')}: <{env}>"

    data: dict[str, Any] = {
        "schema_version": 1,
        "id": pid,
        "title": title or pid.replace("_", " ").title(),
        "distilled_at": date.today().isoformat(),
        "sources": [],
        "openai_compatible": auth == "bearer",
        "high_risk": bool(high_risk),
        "auth": preset,
        "base_urls": {"default": (base_url or "").rstrip("/")},
        "endpoints": [],
        "ops": [
            {"name": "status", "maps_to": f"{pid}.status"},
            {"name": "research", "maps_to": f"{pid}.research"},
        ],
        "errors": {
            "401": "AUTH_DEAD",
            "403": "AUTH_DEAD",
            "429": "RATE_LIMIT",
            "5xx": "PROVIDER_DOWN",
        },
        "limits": {},
        "hub": {
            "probe": True,
            "probe_kind": "status",
            "high_risk": bool(high_risk),
        },
        "notes": [
            "Scaffold generated by `tollgate provider add`. Fill sources, endpoints, ops.",
        ],
    }
    errs = validate_distill(data, path=pid)
    if errs:
        return {"ok": False, "error": "schema", "details": errs}

    if write:
        path.write_text(json.dumps(data, indent=2) + "\n", encoding="utf-8")
        # also suggest keys_app provider block
        cfg_hint = {
            "enabled": not high_risk,
            "priority": 10,
            "high_risk": high_risk,
            "max_calls_day": 100 if high_risk else 1000,
            "max_usd_day": 1.0 if high_risk else 0,
        }
        return {
            "ok": True,
            "path": str(path),
            "id": pid,
            "env_key": env,
            "keys_app_hint": {pid: cfg_hint},
            "next": [
                f"Add {env}=… to User/Key.txt",
                "Merge keys_app_hint into User/keys_app.json providers",
                "Implement thin handler in src/tollgate/<id>.py if needed",
                "Register ops in provider_ops/registry.py",
            ],
        }
    return {"ok": True, "distill": data}
